[ENV]

[asterisk-pg]
enabled => yes
dsn => asterisk-pg
username => asterisk
password => asterisk
pre-connect => yes
; Match postgres max_connections=15 with some headroom for the
; postgres super-user/replication slots.
max_connections => 10
forcecommit => yes
isolation => read_committed
backslash_is_escape => no

; Tight cache so a reload-induced pool drop is visible immediately.
cache_type => stack
cache_size => 10
